name: testing

on:
  push:
    branches: main

jobs:
  my_test_job:
    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: echo "priem, priem"
      
    - name: Create Kafka Topic
      run: bin/kafka-topics.sh --create --topic my_topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
