name: testing

on:
  push:
    branches: main

jobs:
  my_test_job:
    runs-on: ubuntu-latest

    steps:
    - name: install kafka
      uses: bbcCorp/kafka-actions@v1
      with:
        kafka version: latest
        zookeeper version: latest
        kafka port: 9092
        zookeeper port: 2181
      
      
    - name: Create Kafka Topic
      run: bin/kafka-topics.sh --create --topic my_topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
